
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  imageName: "gsaurer/fhwn19-node-app"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: dockerHub
          - task: Docker@2
            displayName: Build image and pus to registry
            inputs:
              command: buildAndPush
              repository: $(imageName)
              dockerfile: "**/Dockerfile"
              containerRegistry: |
                dockerHub
              tags: |
                latest

          # Docker
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'fhwn-19'
              command: 'apply'
              useConfigurationFile: true
              configuration: 'Kubernetes.yaml'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'