apiVersion: v1
kind: Service
metadata:
  name: fhwn19-node-app
  labels:
    app: fhwn19-node-app
spec:
  ports:
    - port: 80
  selector:
    app: fhwn19-node-app
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: fhwn19-node-app
  labels:
    app: fhwn19-node-app
spec:
  selector:
    matchLabels:
      app: fhwn19-node-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fhwn19-node-app
        tier: frontend
    spec:
      containers:
        - image: gsaurer/fhwn19-node-app:latest
          name: fhwn19-node-app
          ports:
            - containerPort: 8080
              name: fhwn19-node-app
